### ISSUE TITLE
[Suggestion] Disable enchantments?/Hide from Enchanting table

### ISSUE THREAD

**Issue by Akitori** [Darkhax-Minecraft/More-Swords-Legacy#1]
Hi! I wanted to ask if its possible to hide enchantments from the enchanting table/remove them? I was going to use the general allow weapons to use enchantments, but then i saw the effects of extinction. Yeahhh, don't want my players killing all chickens in the world with that.

**Comment by Darkhax** [comment]
Hey Akitori, it's been a while :p

The extinction and stealth enchantments are not meant to be obtainable in survival. I will tweet this in the next update so they are not enabled.

**Comment by Darkhax** [comment]
This should be fixed by https://github.com/Darkhax-Minecraft/More-Swords-Legacy/commit/189dea9078038e839a116d6f1432957b2b033b99 and https://github.com/Darkhax-Minecraft/More-Swords-Legacy/commit/985ca8b919bc2ad2e6d57650c2aa441ec56cf817
