### ISSUE TITLE
[Issue] Warns in the server console

### ISSUE THREAD

**Issue by Taknax** [Darkhax-Minecraft/More-Swords-Legacy#10]
I got this in my server console.
[https://pastebin.com/dkkYq4Ee](url)

I use Minecraft 1.12.2 and the new forge 14.23.5.2855.

**Comment by Darkhax** [comment]
Thanks for the report. 1.12.2 is a very old version that is no longer supported. I will look into releasing a patch but that may not happen. The issue is caused by malfunctioning JEI support, installing JEI should resolve the issue.

**Comment by Darkhax** [comment]
Since this is not a fatal issue, this is definitely not getting a special patch.

**Comment by Taknax** [comment]
Ok. Thanks.
