### ISSUE TITLE
Enchantments have no functions in 1.20.4 with fabric

### ISSUE THREAD

**Issue by a23879529** [Darkhax-Minecraft/More-Swords-Legacy#12]
Hi Darkhax,
I want to play this exciting mod in my 1.20.4 Fabric server. I have installed MoreSwordsLegacy-Fabric-1.20.4-5.0.1.jar and Bookshelf-Fabric-1.20.4-23.0.2.jar in both client and server sides, but in the game none of these swords' enchantments are functional.
Please help me, thank you.

**Comment by Darkhax** [comment]
Hello, the enchantments appear to be working perfectly fine on those versions. Could you provide more detail about what you mean?

**Comment by a23879529** [comment]
Hi, thank you for your reply. Sorry for confusing you. I mean when using anvil to enchantments, e.g., Ascension on iron sword, it works perfectly, but when I normally crafted Aethers Guard or other swords in surviving mode or take it in created mode, it doesn't have any special effect as their description, e.g., Ascension and Sky's Grace.

**Comment by Darkhax** [comment]
The enchantments are only given to the sword when you use the enchantment table, and it's not always guaranteed to give you the enchantments you want. You can use other aspects of the enchantment system like the Grindstone to remove enchantments and use enchanted books and the anvil to ensure you get the enchantments you want.

**Comment by a23879529** [comment]
Ok, so these mod's swords are not enchanted their own unique enchantments when they are created, have I got that right?

**Comment by Darkhax** [comment]
Yes, they are not automatically enchanted when you craft them. You need to use the enchantment table.
