### ISSUE TITLE
[BUG] Getting Duplicate Enchantments from Enchanting Table

### ISSUE THREAD

**Issue by knavesmith** [Darkhax-Minecraft/More-Swords-Legacy#13]
### Minecraft Version

1.20.1

### Mod Version

2.0.3

### Mod Loader

Forge

### What environment are you running the mod in?

Client

### Issue Description

I realize I'm on an outdated version of More Swords Legacy, but this is the most up-to-date version for Minecraft 1.20.1. My Forge is version 47.2.0.

When enchanting swords, More Swords Legacy enchantments can be applied multiple times to the same sword.
![image](https://github.com/Darkhax-Minecraft/More-Swords-Legacy/assets/47680346/36922ca3-c9af-4756-a5ee-fb7e4d0148cb)
![image](https://github.com/Darkhax-Minecraft/More-Swords-Legacy/assets/47680346/377de6b2-3b8f-4d4e-8bc0-4c3da71dfa9e)

This is using the default config values for this version.

**Comment by Darkhax** [comment]
Thanks for letting me know about this issue. There are a few issues going on here that should hopefully be pretty quick fixes.

**Comment by Darkhax** [comment]
This issue has been fixed in [2.0.4 for MC 1.20.1](https://www.curseforge.com/minecraft/mc-mods/more-swords-legacy/files/5122054).
