### ISSUE TITLE
[Version Port ETA] What is the approx ETA for a 1.20.6 release of the mod?

### ISSUE THREAD

**Issue by NotIntruder** [Darkhax-Minecraft/More-Swords-Legacy#14]
### Question

What is the approx ETA for a 1.20.6 release of the mod? I am really looking forward to using it in a SMP.
Thanks!

**Comment by Darkhax** [comment]
Hello, this is the statement from my Discord. The TLDR is that they won't be coming any time soon.

![image](https://github.com/Darkhax-Minecraft/More-Swords-Legacy/assets/2250798/3f08c723-d928-497e-b7eb-57ddb4696f01)
