### ISSUE TITLE
Keen Edge doesn't change damage tooltip

### ISSUE THREAD

**Issue by richardmv** [Darkhax-Minecraft/More-Swords-Legacy#3]
I noticed that whenever I add keen edge to a weapon it doesn't display the change to the weapon's damage in its tooltip, but the weapon is definitely more powerful. Would there be a way to have the enchantment update/change the tooltip?

**Comment by Darkhax** [comment]
Yeah, this should be possible to add. Thanks for the suggestion.

**Comment by Darkhax** [comment]
The tooltip now updates properly.
