### ISSUE TITLE
More Swords legacy crashing when loading Minecraft

### ISSUE THREAD

**Issue by USAgamerrr** [Darkhax-Minecraft/More-Swords-Legacy#5]
I get this crash when I try to load up Minecraft any idea how to fix it?

 ---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  midnight (themidnight-0.3.5.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.5.6-core.jar)
  AstralCore (astralsorcery-1.12.2-1.10.12.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.13-universal.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 2/9/20 7:49 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from More Swords Legacy (msmlegacy)
Caused by: java.lang.NoSuchMethodError: net.darkhax.bookshelf.registry.RegistryHelper.registerEnchantment(Lnet/minecraft/enchantment/Enchantment;Ljava/lang/String;)Lnet/minecraft/enchantment/Enchantment;
	at net.darkhax.msmlegacy.MSMLegacy.onPreInit(MSMLegacy.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1485611128 bytes (1416 MB) / 2214592512 bytes (2112 MB) up to 12884901888 bytes (12288 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 92 mods loaded, 92 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version                  | Source                                            | Signature                                |
	|:----- |:-------------------- |:------------------------ |:------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft            | 1.12.2                   | minecraft.jar                                     | None                                     |
	| LCH   | mcp                  | 9.42                     | minecraft.jar                                     | None                                     |
	| LCH   | FML                  | 8.0.99.99                | forge-1.12.2-14.23.5.2838.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                | 14.23.5.2838             | forge-1.12.2-14.23.5.2838.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | jei                  | 4.15.0.268               | jei_1.12.2-4.15.0.268.jar                         | None                                     |
	| LCH   | abyssalcraft         | 1.9.6                    | AbyssalCraft-1.12.2-1.9.6.jar                     | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCH   | aether_legacy        | 1.12.2-v1.4.3            | aether_legacy-1.12.2-v1.4.3.jar                   | None                                     |
	| LCH   | applecore            | 3.2.0                    | AppleCore-mc1.12.2-3.2.0.jar                      | None                                     |
	| LCH   | appleskin            | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                        | None                                     |
	| LCH   | baubles              | 1.5.2                    | Baubles-1.12-1.5.2.jar                            | None                                     |
	| LCH   | astralsorcery        | 1.10.12                  | astralsorcery-1.12.2-1.10.12.jar                  | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LCH   | atum                 | 2.0.16                   | Atum-1.12.2-2.0.16.jar                            | None                                     |
	| LCH   | backpack             | 3.0.2                    | backpack-3.0.2-1.12.2.jar                         | None                                     |
	| LCH   | betterbedrockgen     | 6.0.2                    | BetterBedrockGenerator-1.12-6.1.1.jar             | None                                     |
	| LCH   | blue_skies           | 1.1.3                    | blue_skies-1.12.2-v1.1.3.jar                      | None                                     |
	| LCH   | bookshelf            | 2.3.577                  | Bookshelf-1.12.2-2.3.577.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | carbonado            | 1.4.2                    | carbonado-1.4.2-mc1.12.x.jar                      | None                                     |
	| LCH   | codechickenlib       | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | chickenchunks        | 2.4.1.73                 | ChickenChunks-1.12.2-2.4.1.73-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | clienttweaks         | 3.1.11                   | ClientTweaks_1.12.2-3.1.11.jar                    | None                                     |
	| LCH   | mantle               | 1.12-1.3.3.49            | Mantle-1.12-1.3.3.49.jar                          | None                                     |
	| LCH   | twilightforest       | 3.8.689                  | twilightforest-1.12.2-3.8.689-universal.jar       | None                                     |
	| LCH   | tconstruct           | 1.12.2-2.13.0.171        | TConstruct-1.12.2-2.13.0.171.jar                  | None                                     |
	| LCH   | conarm               | 1.2.5.3                  | conarm-1.12.2-1.2.5.3.jar                         | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCH   | extendedrenderer     | v1.0                     | coroutil-1.12.1-1.2.31.jar                        | None                                     |
	| LCH   | coroutil             | 1.12.1-1.2.31            | coroutil-1.12.1-1.2.31.jar                        | None                                     |
	| LCH   | configmod            | v1.0                     | coroutil-1.12.1-1.2.31.jar                        | None                                     |
	| LCH   | miccw                | 1.0                      | CosmicArmory-1.6.jar                              | None                                     |
	| LCH   | craftingtweaks       | 8.1.9                    | CraftingTweaks_1.12.2-8.1.9.jar                   | None                                     |
	| LCH   | defiledlands         | 1.4.2                    | defiledlands-1.12.2-1.4.2 (1).jar                 | None                                     |
	| LCH   | dimdoors             | 3.0.9+287                | DimensionalDoors-3.0.9-287.jar                    | None                                     |
	| LCH   | eleccore             | 1.9.452                  | ElecCore-1.12.2-1.9.452.jar                       | None                                     |
	| LCH   | forbidden_arcanus    | 1.12.2-1.1.1             | forbidden_arcanus-1.12.2-1.1.1.jar                | None                                     |
	| LCH   | forgelin             | 1.8.2                    | Forgelin-1.8.2.jar                                | None                                     |
	| LCH   | tschipplib           | 1.1.3                    | TschippLib+MC1.12.2+v1.1.3.jar                    | None                                     |
	| LCH   | forgottenitems       | 1.2.1                    | ForgottenItems+MC1.12.2+v1.2.1.jar                | None                                     |
	| LCH   | llibrary             | 1.7.18                   | llibrary-1.7.18-1.12.2.jar                        | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCH   | fossil               | 8.0.0                    | fossilsarcheology-8.0.0.jar                       | None                                     |
	| LCH   | fw                   | 1.6.0                    | FullscreenWindowed-1.12-1.6.0.jar                 | None                                     |
	| LCH   | gravestone           | 1.10.1                   | gravestone-1.10.1.jar                             | None                                     |
	| LCH   | guideapi             | 1.12-2.1.8-63            | Guide-API-1.12.2.jar                              | None                                     |
	| LCH   | placebo              | 1.6.0                    | Placebo-1.12.2-1.6.0.jar                          | None                                     |
	| LCH   | hexxitgear           | 2.8.0                    | Hexxit+Gear-1.12.2-2.8.0.jar                      | None                                     |
	| LCH   | huds                 | #VERSION#                | Huds-1.12.2-1.0.3.jar                             | None                                     |
	| LCH   | huntingdim           | 1.0.36                   | HuntingDimension-1.12.2-1.0.36.jar                | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | waila                | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                       | None                                     |
	| LCH   | infernalmobs         | 1.7.5                    | InfernalMobs-1.12.2.jar                           | None                                     |
	| LCH   | ironchest            | 1.12.2-7.0.40.824        | ironchest-1.12.2-7.0.40.824.jar                   | None                                     |
	| LCH   | journeymap           | 1.12.2-5.5.4             | journeymap-1.12.2-5.5.4.jar                       | None                                     |
	| LCH   | labyrinth            | ${version}               | Labyrinth-1.12.2-1.0.jar                          | None                                     |
	| LCH   | lex                  | 1.0.8                    | LibEx-1.12.2-1.0.8.jar                            | None                                     |
	| LCH   | lightningcraft       | 2.9.7_1                  | lightningcraft-2.9.7_1.jar                        | None                                     |
	| LCH   | lost_aether          | 0.0.3                    | lost_aether-content-1.12.2-v0.0.3.jar             | None                                     |
	| LCH   | materialchanger      | 1.0                      | materialchanger1.0.3-1.12.2.jar                   | None                                     |
	| LCH   | moreoverlays         | 1.14                     | moreoverlays-1.14-mc1.12.2.jar                    | None                                     |
	| LCE   | msmlegacy            | @VERSION@                | MoreSwordsLegacy-1.12.2-1.0.4.jar                 | None                                     |
	| LC    | mowziesmobs          | 1.5.3                    | mowziesmobs-1.5.3.jar                             | None                                     |
	| LC    | mystcraft            | 0.13.7.03                | mystcraft-1.12.2-0.13.7.03.jar                    | None                                     |
	| LC    | naturescompass       | 1.5.1                    | NaturesCompass-1.12.2-1.5.1.jar                   | None                                     |
	| LC    | nex                  | 2.0.8                    | NetherEx-1.12.2-2.0.8.jar                         | None                                     |
	| LC    | nei                  | 2.4.2                    | NotEnoughItems-1.12.2-2.4.2.240-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | oppositedimensions   | 3.0.0                    | Opposite+Dimensions+3.0.0.jar                     | None                                     |
	| LC    | pagamos              | 0.0.1                    | pagamos-1.12.2-0.0.1.jar                          | None                                     |
	| LC    | pirates              | 0.0.5                    | pirates-0.0.5A.jar                                | None                                     |
	| LC    | progressivebosses    | 1.4.1                    | ProgressiveBosses-1.4.1-mc1.12.x.jar              | None                                     |
	| LC    | reap                 | 1.5.0                    | reap-1.5.0.jar                                    | None                                     |
	| LC    | repairgem            | 1.3.0                    | RepairGem-1.12.2-1.3.0.jar                        | None                                     |
	| LC    | additionalstructures | 2.3.1                    | Rex's-Additional-Structures-1.12.x-(v.2.3.1).jar  | None                                     |
	| LC    | roguelike            | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar                | None                                     |
	| LC    | ruins                | 17.1                     | Ruins-1.12.2.jar                                  | None                                     |
	| LC    | sereneseasons        | 1.2.13                   | SereneSeasons-1.12.2-1.2.13-universal.jar         | None                                     |
	| LC    | silentlib            | 3.0.13                   | SilentLib-1.12.2-3.0.13+167.jar                   | None                                     |
	| LC    | soulshardstow        | 1.12-2.7.6-56            | SoulShards-TOW-1.12-2.7.6-56.jar                  | None                                     |
	| LC    | tammodized           | 0.15.6                   | TamModized-1.12.2-0.15.6.jar                      | None                                     |
	| LC    | theeightfabledblades | 1.0.0                    | TheEightFabledBlades+V2.0.01.jar                  | None                                     |
	| LC    | tinkersjei           | 1.1                      | tinkersjei-1.1.jar                                | None                                     |
	| LC    | tinkertoolleveling   | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar               | None                                     |
	| LC    | tirphycraft          | 0.2                      | tirphycraft_B_1.12.2_1.0.jar                      | None                                     |
	| LC    | travellersboots      | 1.0.4                    | travellersboots-1.12.2-1.0.4.jar                  | None                                     |
	| LC    | uteamcore            | 2.2.4.94                 | u_team_core-1.12.2-2.2.4.94.jar                   | None                                     |
	| LC    | undergroundbiomes    | 1.3.2                    | UndergroundBiomesConstructs-1.12-1.3.2.jar        | None                                     |
	| LC    | veinminer            | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar             | None                                     |
	| LC    | veinminermodsupport  | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar             | None                                     |
	| LC    | volcanicevolution106 | 1.0.6                    | Volcanic+Evolution+-+1.0.6.jar                    | None                                     |
	| LC    | waystones            | 4.0.62                   | Waystones_1.12.2-4.0.62.jar                       | None                                     |
	| LC    | weather2             | 1.12.1-2.6.12            | weather2-1.12.1-2.6.12.jar                        | None                                     |
	| LC    | wildnature           | 1.1                      | wildnature-1.1.jar                                | None                                     |
	| LC    | worldedit            | 6.1.10-SNAPSHOT          | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar | None                                     |
	| LC    | zerocore             | 1.12.2-0.1.2.8           | zerocore-1.12.2-0.1.2.8.jar                       | None                                     |
	| LC    | thebetweenlands      | 3.5.6                    | TheBetweenlands-3.5.6-universal.jar               | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| LC    | midnight             | 0.3.5                    | themidnight-0.3.5.jar                             | None                                     |
	| LC    | eleccoreloader       | 1.9.452                  | ElecCore-1.12.2-1.9.452.jar                       | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
midnight (themidnight-0.3.5.jar)
  com.mushroom.midnight.core.transformer.MidnightClassTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.5.6-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
AstralCore (astralsorcery-1.12.2-1.10.12.jar)
  
ForgelinPlugin (Forgelin-1.8.2.jar)
  
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.13-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 436.48' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

**Comment by Darkhax** [comment]
You are using an outdated version of Bookshelf.
