### ISSUE TITLE
JEI suggests enchanting anvils or Hellshelfs with enchants from this mod when Apotheosis is also installed

### ISSUE THREAD

**Issue by RnChan408** [Darkhax-Minecraft/More-Swords-Legacy#8]
When this mod, Apotheosis and JEI are installed, JEI shows recipes to add Venomous Aspect to Hellshelfs and Frozen Aspect to anvils despite being unable to do so in survival at all.  JEI Hellshelves enchanted with Venomous Aspect can also be seen when searching for Hellfshelves. 

![image](https://user-images.githubusercontent.com/14255073/99072452-0965a580-25ef-11eb-98be-79328368b0e2.png)
![image](https://user-images.githubusercontent.com/14255073/99072416-f226b800-25ee-11eb-8003-b90bc7edf855.png)
![image](https://user-images.githubusercontent.com/14255073/99072499-2306ed00-25ef-11eb-9216-0a6c06164d70.png)

**Comment by Darkhax** [comment]
This seems like an issue with Apotheosis not checking `canApplyAtEnchantingTable`.
